Locking in RedisSessionHandler::open() is not required
In fact it is wrong, because session than throws stupid errors like

> Fatal error: session_start(): No session id returned by function